### ISSUE TITLE
TypeError: descriptor 'encode' requires a 'str' object but received a 'bytes'

### ISSUE THREAD

**Issue by ArchaeOphelie** [ktmeaton/NCBImeta#25]
Hello, 
I've tried running both the example config file and my own, but come across the following issue:  

ID: 8874191
Processing record: 1/211
Traceback (most recent call last):
  File "./NCBImeta.py", line 630, in <module>
    FORCE_PAUSE_SECONDS,
  File "./NCBImeta.py", line 453, in UpdateDB
    temp_b.write(str.encode(line))
TypeError: descriptor 'encode' requires a 'str' object but received a 'bytes'

I'm quite new to bioinformatics, but is this an issue with the code? Thank you!

**Comment by ArchaeOphelie** [comment]
My apologies, I found the issue, which was that running 'conda install -c bioconda ncbimeta' installed an order version of NCBImeta, and not the latest version. It seems to be currently working.

**Comment by ktmeaton** [comment]
Thank you for documenting and troubleshooting this error! I will investigate why the conda package is out of date.
